CREATE TABLE deposit_conditions
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deposit_type_id               BIGINT                                  NOT NULL,
    is_top_up_allowed             BOOLEAN,
    is_partial_withdrawal_allowed BOOLEAN,
    minimum_balance               DECIMAL,
    interest_payment_frequency    VARCHAR(255),
    CONSTRAINT pk_deposit_conditions PRIMARY KEY (id)
);

CREATE TABLE deposit_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_deposittype PRIMARY KEY (id)
);

CREATE TABLE deposits
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id       BIGINT,
    contract_number VARCHAR(255),
    deposit_type_id BIGINT                                  NOT NULL,
    contract_amount DECIMAL,
    interest_rate   DECIMAL,
    contract_term   INTEGER,
    conclusion_date date,
    end_date        date,
    status          VARCHAR(255),
    CONSTRAINT pk_deposits PRIMARY KEY (id)
);

CREATE TABLE operations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deposit_id     BIGINT,
    operation_type VARCHAR(255),
    amount         DECIMAL,
    operation_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_operations PRIMARY KEY (id)
);

ALTER TABLE deposit_conditions
    ADD CONSTRAINT uc_deposit_conditions_deposit_type UNIQUE (deposit_type_id);

ALTER TABLE deposits
    ADD CONSTRAINT uc_deposits_contractnumber UNIQUE (contract_number);

ALTER TABLE deposit_type
    ADD CONSTRAINT uc_deposittype_name UNIQUE (name);

ALTER TABLE deposits
    ADD CONSTRAINT FK_DEPOSITS_ON_DEPOSIT_TYPE FOREIGN KEY (deposit_type_id) REFERENCES deposit_type (id);

ALTER TABLE deposit_conditions
    ADD CONSTRAINT FK_DEPOSIT_CONDITIONS_ON_DEPOSIT_TYPE FOREIGN KEY (deposit_type_id) REFERENCES deposit_type (id);

ALTER TABLE operations
    ADD CONSTRAINT FK_OPERATIONS_ON_DEPOSIT FOREIGN KEY (deposit_id) REFERENCES deposits (id);