server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/client_db
    #url: jdbc:postgresql://localhost:5432/clientService
    password: 'postgres'
    username: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health