server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # включаем автоматическое определение сервисов
          lowerCaseServiceId: true
      routes:
        - id: client-service
          uri: lb://client-service  # lb:// означает использование Load Balancer
          predicates:
            - Path=/api/v1.0/clients/**
        - id: loan-service
          uri: lb://loan-service  # lb:// означает использование Load Balancer
          predicates:
            - Path=/api/loans/**
        - id: deposit-service
          uri: lb://deposit-service  # lb:// означает использование Load Balancer
          predicates:
            - Path=/api/v1.0/deposits/**

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: health
