services:
  postgres_client:
    container_name: loan_service
    image: postgres:16
    environment:
      POSTGRES_DB: loanService
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_loan:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  postgres_loan: