CREATE TABLE loans
(
    loan_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id       BIGINT,
    contract_number VARCHAR(255)                            NOT NULL,
    product_type    SMALLINT,
    loan_amount     DECIMAL,
    interest_rate   DECIMAL,
    loan_term       INTEGER,
    contract_date   date,
    end_date        date,
    status          VARCHAR(255)                            NOT NULL,
    current_debt    DECIMAL,
    CONSTRAINT pk_loans PRIMARY KEY (loan_id)
);

CREATE TABLE payment_history
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loan_id      BIGINT,
    payment_date TIMESTAMP WITHOUT TIME ZONE,
    amount_paid  DECIMAL,
    payment_type VARCHAR(255),
    status       VARCHAR(255),
    CONSTRAINT pk_payment_history PRIMARY KEY (id)
);

CREATE TABLE payment_schedule
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loan_id          BIGINT,
    payment_date     date,
    principal_amount DECIMAL,
    interest_amount  DECIMAL,
    total_amount     DECIMAL,
    status           VARCHAR(255),
    CONSTRAINT pk_payment_schedule PRIMARY KEY (id)
);

ALTER TABLE loans
    ADD CONSTRAINT uc_loans_contract_number UNIQUE (contract_number);

ALTER TABLE payment_history
    ADD CONSTRAINT FK_PAYMENT_HISTORY_ON_LOAN FOREIGN KEY (loan_id) REFERENCES loans (loan_id);

ALTER TABLE payment_schedule
    ADD CONSTRAINT FK_PAYMENT_SCHEDULE_ON_LOAN FOREIGN KEY (loan_id) REFERENCES loans (loan_id);